name: Run tests

on:
  push:
    branches: ['*']
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip 
          pip install mcp[cli]==1.9.3, pytest-asyncio==1.0.0

      - name: Free space
        run: df -h && rm -rf /opt/hostedtoolcache* && df -h

      - name: Run tests
        run: |-
          pytest tests
        env:
          QUANTCONNECT_USER_ID: ${{ secrets.QUANTCONNECT_USER_ID }}
          QUANTCONNECT_API_TOKEN: ${{ secrets.QUANTCONNECT_API_TOKEN }}
