name: Run tests

on:
  push:
    branches: ['*']
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip 
          pip install httpx==0.28.1, mcp[cli]==1.9.3, pytest==8.4.1

      - name: Free space
        run: df -h && rm -rf /opt/hostedtoolcache* && df -h

      - name: Run tests
        run: |-
          pytest tests
